// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

// This is a placeholder for the Verifier.sol generated by bb write_solidity_verifier.
// The actual content will be generated on the physical device.

interface IVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}

